spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能, 利用微服务名进行路由
          enabled: true
      routes:
          # 路由ID
        - id: service-a
          # 目标服务地址
          uri: lb://service-a
          # 路由条件, 该接口包含多种默认方法来将 predicate 组合成其他复杂的逻辑(比如: 与, 或, 非).
          predicates:
            - Path=/service-a/**

        - id: service-b
          uri: lb://service-b
          predicates:
            - Path=/service-b/**
